FROM metabrainz/consul-template-base:0.18.2

MAINTAINER Robert Kaye <rob@metabrainz.org>

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        bsdmainutils \
        ca-certificates \
        curl \
        git \
        maven \
        openjdk-8-jdk \
        psmisc \
        python \
        rsync

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN cd /tmp && \
    git clone https://github.com/metabrainz/mmd-schema.git && \
    cd mmd-schema/brainz-mmd2-jaxb && \
    mvn install && \
    cd /

RUN groupadd -r jetty && \
    useradd -r -g jetty jetty

ARG JETTY_VERSION=9.4.5.v20170502
ARG JETTY_DIST=jetty-distribution-$JETTY_VERSION

RUN cd /tmp && \
    curl -o jetty.tar.gz http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/$JETTY_VERSION/$JETTY_DIST.tar.gz && \
    tar -xvzf jetty.tar.gz && \
    mv $JETTY_DIST /usr/local/jetty && \
    rm jetty.tar.gz

ENV JETTY_HOME /usr/local/jetty
ENV PATH $JETTY_HOME/bin:$PATH
ENV SEARCH_HOME=/home/search

WORKDIR $SEARCH_HOME

RUN mkdir search-server-code
COPY pom.xml search-server-code/
COPY index/ search-server-code/index/
COPY servlet/ search-server-code/servlet/

RUN cd search-server-code && \
    sed -i 's/^\s*<module>updater<\/module>\s*$//g' pom.xml && \
    mvn package && \
    mv servlet/target/searchserver.war $JETTY_HOME/webapps/ROOT.war && \
    cd $SEARCH_HOME && \
    rm -rf search-server-code

ENV INDEXES_VERSION=1
ENV RSYNC_PASSWORD=search

RUN mkdir bin
COPY docker/server/server.sh bin/
COPY docker/server/server.service /etc/service/server/run
RUN chmod 755 /etc/service/server/run

# Configuration
COPY \
    docker/server/consul-template-server.conf \
    docker/server/RSYNC_SERVER.ctmpl \
    /etc/
