FROM metabrainz/consul-template-base:0.18.2

MAINTAINER Robert Kaye <rob@metabrainz.org>

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        bsdmainutils \
        ca-certificates \
        curl \
        git \
        maven \
        openjdk-8-jdk \
        psmisc \
        python \
        rsync

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN cd /tmp && \
    git clone https://github.com/metabrainz/mmd-schema.git && \
    cd mmd-schema/brainz-mmd2-jaxb && \
    mvn install && \
    cd /

# Install search indexer stuff
ENV INDEXES_VERSION=1
ENV SEARCH_HOME=/home/search

WORKDIR $SEARCH_HOME

RUN mkdir -p bin indexdata rsync
COPY indexer/rsyncd.conf /etc
COPY indexer/rsync.secrets /etc
RUN chmod og-rw /etc/rsync.secrets

COPY index index-code
RUN cd index-code && \
    mvn package && \
    cd $SEARCH_HOME && \
    mv index-code/target/index-2.0-SNAPSHOT-jar-with-dependencies.jar index.jar && \
    rm -rf index-code

# Install the scripts
COPY \
    docker/indexer/build-indexes.sh \
    docker/indexer/indexer.py \
    $SEARCH_HOME/bin/
COPY docker/indexer/indexer.service /etc/service/indexer/run
RUN chmod 755 /etc/service/indexer/run

# Configuration
COPY docker/indexer/consul-template-indexer.conf /etc/
COPY docker/indexer/consul_indexer_config.ini.ctmpl /code/
